### ISSUE TITLE
太棒了！欢迎！我认为这是一次愉快的会议！

### ISSUE THREAD

**Issue by yeyutian205** [filecoin-project/community#22]
名称：王继东
邮箱：duck-baby@163.com
附属机构：星通科技
Github句柄：非常期待本次活动
我将参与本次活动

**Comment by 15000402842** [comment]
时间地址在哪里？


    


            在2019年07月13日 12:56，yeyutian205 写道： 名称：王继东

邮箱：duck-baby@163.com

附属机构：星通科技

Github句柄：非常期待本次活动

闪电谈话主题 :无



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/filecoin-project/community/issues/22?email_source=notifications\u0026email_token=AI7RFHZAEQ2T3HDM5RGTRJTP7FOBPA5CNFSM4ICWYC5KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G7ADFKQ",

"url": "https://github.com/filecoin-project/community/issues/22?email_source=notifications\u0026email_token=AI7RFHZAEQ2T3HDM5RGTRJTP7FOBPA5CNFSM4ICWYC5KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G7ADFKQ",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
